# Generated by Django 4.1.2 on 2022-12-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('idNumber', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('residence', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('nationId', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'InActive')], default='I', max_length=1)),
                ('kra', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('nationId',),
            },
        ),
        migrations.CreateModel(
            name='NOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('idNumber', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nok', to='accounts.user')),
            ],
            options={
                'ordering': ('idNumber',),
            },
        ),
    ]
