# Generated by Django 4.1.2 on 2022-12-01 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'InActive')], default='I', max_length=1)),
                ('balance', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('acc_number',),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('A', 'Alive'), ('D', 'Dead')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=50)),
                ('teller', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='accounts.account')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accounts.user'),
        ),
    ]
