# Generated by Django 4.1.2 on 2022-12-01 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction_transactionstatus_alter_transaction_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='TransactionStatus',
            new_name='transactionStatus',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default=uuid.UUID('263b496e-7166-11ed-adc5-4851b7b990fa'), max_length=50),
        ),
    ]
