# Generated by Django 4.1.2 on 2022-12-01 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_transactionstatus_transaction_transactionstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(default=uuid.UUID('29fc5a36-7175-11ed-87e7-4851b7b990fa'), max_length=50),
        ),
    ]
